# alacritty configuration toml
# used as main entrypoint for alacritty configurations

# based on a toml example configuration
# https://github.com/alacritty/alacritty/issues/6999#issuecomment-1903342590

# imports are loaded in order, skipping all missing files
# if a field is already present in a previous import it will be replaced
# all imports must either be absolute paths starting with _/_
# or paths relative to the user's home directory starting with _~/_
import = [
  "~/.config/alacritty/keybindings.toml", # custom keybindings
]

# ----- ----- ----- -----

# windows appearance customization
[window]
padding = { x = 15, y = 15 }
option_as_alt = "OnlyLeft"

# ----- ----- ----- -----

# control windows scrolling
[scrolling]
multiplier = 5

# ----- ----- ----- -----

# set terminal fonts
[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 12

# ----- ----- ----- -----

# change cursor appearance
[cursor]
style.blinking = "Always"
blink_interval = 300

# ----- ----- ----- -----

# mouse settings when using emulator
[mouse]
hide_when_typing = true

# ----- ----- ----- -----

# set theme colors
# Tokyo Night color theme
# based on https://github.com/enkia/tokyo-night-vscode-theme?tab=readme-ov-file#tokyo-night-and-tokyo-night-storm
# sourced https://github.com/folke/tokyonight.nvim/blob/main/extras/alacritty/tokyonight_night.toml

# default colors
[colors.primary]
background = '#1a1b26'
foreground = '#acb0cd'

# default cursor colors
[colors.cursor]
cursor = '#c0caf5'

# normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# bright colors
[colors.bright]
black = '#414868'
red = '#e67e8f'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# indexed colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

